/**
 * src/lib/lead.ts
 *
 * Canonical lead shape, phone normalisation, and lead-reference generation.
 * Pure functions — no side effects, no I/O. Safe on both server and client.
 */

import type { Attribution } from './attribution';

// ─── Lead reference ───────────────────────────────────────────────────────────

const BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

/**
 * Generate a short, collision-resistant lead reference.
 * "PW-" + 5 uppercase base32 characters derived from crypto.randomUUID().
 * Example: "PW-8F3K2"
 *
 * 5 × 5 bits = 25 bits from the first 32 bits of the UUID → ~33M combinations.
 * This is OUR reference — it must not be derived from any third-party system ID.
 */
export function leadRef(prefix = 'PW'): string {
  const hex = crypto.randomUUID().replace(/-/g, '').slice(0, 8); // 32 bits
  let n     = parseInt(hex, 16) >>> 0;                           // safe: 32-bit uint
  let chars = '';
  for (let i = 0; i < 5; i++) {
    chars = BASE32[n & 31] + chars;
    n     = n >>> 5;
  }
  return prefix + '-' + chars;
}

// ─── Phone normalisation ──────────────────────────────────────────────────────

/**
 * Normalise an Australian phone number to E.164 format (+61XXXXXXXXX).
 * This is the join key to Xero, so it must be consistent across all leads.
 *
 * Handles:
 *   04XX XXX XXX → +614XXXXXXXX  (mobile)
 *   0[2-9] XXXX XXXX → +61[2-9]XXXXXXXX  (landline)
 *   +61... → passed through after stripping formatting
 *   61...  → +61...
 *
 * Returns the original trimmed string if it cannot be normalised.
 */
export function normalisePhoneE164(raw: string): string {
  const stripped = raw.replace(/[\s\-().]/g, '');

  // Already has +61 prefix
  if (/^\+61[2-9]\d{8}$/.test(stripped)) return stripped;

  // Digits only from here
  const digits = stripped.replace(/^\+/, '');

  // 61XXXXXXXXX (without leading +)
  if (/^61[2-9]\d{8}$/.test(digits)) return '+' + digits;

  // 04XXXXXXXX → +614XXXXXXXX
  if (/^04\d{8}$/.test(digits)) return '+61' + digits.slice(1);

  // 0[2-9]XXXXXXXX → +61[2-9]XXXXXXXX
  if (/^0[2-9]\d{8}$/.test(digits)) return '+61' + digits.slice(1);

  return raw.trim();
}

// ─── Lead type ────────────────────────────────────────────────────────────────

export interface Lead {
  lead_ref:    string;
  created_at:  string;
  name:        string;
  company:     string;
  email:       string;
  phone:       string;
  phone_e164:  string;
  suburb:      string;
  service_type: string;
  industry:    string;
  message:     string;
  source_form: string;
  attribution: Attribution;
}

// ─── buildLead ────────────────────────────────────────────────────────────────

function s(v: unknown): string {
  return typeof v === 'string' ? v.trim() : '';
}

/**
 * Normalise raw form fields + attribution into a canonical Lead object.
 *
 * @param form        Raw string values from the form body (server-side Record).
 * @param attribution Attribution object sent by the client.
 * @param ref         Lead reference generated by leadRef().
 */
export function buildLead(
  form:        Partial<Record<string, string>>,
  attribution: Attribution,
  ref:         string,
): Lead {
  const phone = s(form.phone);

  const name =
    s(form.name) ||
    s(form.full_name) ||
    [s(form.firstname ?? form.firstName), s(form.lastname ?? form.lastName)]
      .filter(Boolean)
      .join(' ');

  return {
    lead_ref:    ref,
    created_at:  new Date().toISOString(),
    name,
    company:     s(form.company ?? form.company_name ?? form.companyName),
    email:       s(form.email).toLowerCase(),
    phone,
    phone_e164:  normalisePhoneE164(phone),
    suburb:      s(form.suburb ?? form.location ?? form.projectLocation ?? form.project_location),
    service_type: s(form.service_type ?? form.service ?? form.projectType ?? form.project_type),
    industry:    s(form.industry),
    message:     s(form.message ?? form.description),
    source_form: s(form.source_form),
    attribution,
  };
}
