/**
 * src/lib/notify.ts
 *
 * Primary, guaranteed lead-delivery path via the Resend email API.
 *
 * Design contract
 * ───────────────
 * • sendLeadNotification() THROWS on any failure.
 * • Callers must catch and return HTTP 502 — never swallow errors.
 * • Email is the ONLY guaranteed delivery path; every downstream system
 *   (AroFlo, future CRM) is a non-blocking secondary push.
 *
 * Required env var
 * ────────────────
 * RESEND_API_KEY      Resend API key (resend.com → API Keys)
 *
 * Optional env vars
 * ─────────────────
 * LEAD_NOTIFY_TO      Primary recipient (default: admin@pulseqld.com.au)
 * JOBS_NOTIFY_TO      Careers/jobs recipient (default: accounts@pulseqld.com.au)
 */

const RESEND_API_KEY = import.meta.env.RESEND_API_KEY ?? '';
const FROM_EMAIL     = 'Pulse Website <noreply@pulseqld.com.au>';

export const LEAD_NOTIFY_TO =
  import.meta.env.LEAD_NOTIFY_TO ?? 'admin@pulseqld.com.au';

export const JOBS_NOTIFY_TO =
  import.meta.env.JOBS_NOTIFY_TO ?? 'accounts@pulseqld.com.au';

// ─── Lead reference ───────────────────────────────────────────────────────────

/** Generate a short, unique lead reference, e.g. "PW-8F3K2". */
export function leadRef(): string {
  return 'PW-' + Math.random().toString(36).slice(2, 7).toUpperCase();
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface Attribution {
  pageUri?:     string;
  ipAddress?:   string;
  utmSource?:   string;
  utmMedium?:   string;
  utmCampaign?: string;
}

export interface LeadNotification {
  /** Recipient address. Defaults to LEAD_NOTIFY_TO. */
  to?:           string;
  /** Lead reference generated by leadRef(). */
  ref:           string;
  /**
   * Subject suffix appended after the reference, e.g.
   *   "Blocked Drain — Loganholme — 0412 345 678"
   * Full subject becomes: "[PW-8F3K2] Blocked Drain — Loganholme — 0412 345 678"
   */
  subjectSuffix: string;
  /** Ordered field rows. Empty/undefined values are omitted. */
  fields:        Array<[label: string, value: string | undefined]>;
  attribution?:  Attribution;
}

// ─── sendLeadNotification ─────────────────────────────────────────────────────

/**
 * Send a lead notification email via the Resend API.
 *
 * Throws an Error if:
 *   • RESEND_API_KEY is not configured
 *   • Resend returns a non-2xx response
 *
 * The caller MUST catch this and return HTTP 502.
 */
export async function sendLeadNotification(n: LeadNotification): Promise<void> {
  if (!RESEND_API_KEY) {
    throw new Error('RESEND_API_KEY is not configured — email delivery is unavailable.');
  }

  const to      = n.to ?? LEAD_NOTIFY_TO;
  const subject = `[${n.ref}] ${n.subjectSuffix}`;

  // Filter empty values; keep insertion order
  const dataRows = n.fields.filter(
    (row): row is [string, string] => Boolean(row[1]?.trim()),
  );

  // Attribution block appended below a divider
  const attr = n.attribution ?? {};
  const attrRows: Array<[string, string]> = ([
    ['Lead Ref',     n.ref],
    ['Page',         attr.pageUri    ?? ''],
    ['IP',           attr.ipAddress  ?? ''],
    ['UTM Source',   attr.utmSource  ?? ''],
    ['UTM Medium',   attr.utmMedium  ?? ''],
    ['UTM Campaign', attr.utmCampaign ?? ''],
  ] as Array<[string, string]>).filter(([, v]) => v);

  const allRows  = [...dataRows, ...attrRows];
  const splitAt  = dataRows.length; // index where attribution starts

  // ── Plain text ─────────────────────────────────────────────────────────────
  const text = [
    subject,
    '='.repeat(subject.length),
    '',
    ...dataRows.map(([k, v]) => `${k}: ${v}`),
    ...(attrRows.length ? ['', '--- Attribution ---', ...attrRows.map(([k, v]) => `${k}: ${v}`)] : []),
  ].join('\n');

  // ── HTML ───────────────────────────────────────────────────────────────────
  const cellK = `style="padding:5px 16px 5px 0;font-weight:600;white-space:nowrap;` +
                `vertical-align:top;color:#1a1a1a;font-family:sans-serif;font-size:13px"`;
  const cellV = `style="padding:5px 0;color:#334155;font-family:sans-serif;font-size:13px"`;

  const tableRows = allRows.map(([k, v], i) => {
    const divider = i === splitAt && splitAt > 0 && splitAt < allRows.length
      ? `<tr><td colspan="2" style="padding:12px 0 4px">` +
        `<hr style="border:none;border-top:1px solid #e2e8f0"></td></tr>\n`
      : '';
    return `${divider}<tr><td ${cellK}>${k}</td><td ${cellV}>${v}</td></tr>`;
  }).join('\n');

  const html = `
<div style="max-width:600px;margin:0 auto;font-family:sans-serif;color:#1a1a1a">
  <h2 style="margin:0 0 4px;font-size:18px;color:#0172ae">${subject}</h2>
  <p style="margin:0 0 20px;font-size:12px;color:#94a3b8">
    Pulse Plumbing, Gas &amp; Civil — Lead Notification
  </p>
  <table style="border-collapse:collapse;width:100%">
    ${tableRows}
  </table>
</div>`;

  // ── Send ───────────────────────────────────────────────────────────────────
  const res = await fetch('https://api.resend.com/emails', {
    method:  'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type':  'application/json',
    },
    body: JSON.stringify({ from: FROM_EMAIL, to: [to], subject, html, text }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => String(res.status));
    throw new Error(`Resend rejected the notification (${res.status}): ${detail}`);
  }
}
